gamerule sendcommandfeedback false
give @s ghoulcraft:sawning_black
give @s ghoulcraft:sawning_blue
give @s ghoulcraft:sawning_brown
give @s ghoulcraft:sawning_cyan
give @s ghoulcraft:sawning_gray
give @s ghoulcraft:sawning_green
give @s ghoulcraft:sawning_lblue
give @s ghoulcraft:sawning_lgray
give @s ghoulcraft:sawning_lime
give @s ghoulcraft:sawning_orange
give @s ghoulcraft:sawning_magenta
give @s ghoulcraft:sawning_purple
give @s ghoulcraft:sawning_pink
give @s ghoulcraft:sawning_red
give @s ghoulcraft:sawning_yellow
gamerule sendcommandfeedback true