gamerule sendcommandfeedback false
give @s ghoulcraft:awning_black
give @s ghoulcraft:awning_blue
give @s ghoulcraft:awning_brown
give @s ghoulcraft:awning_cyan
give @s ghoulcraft:awning_gray
give @s ghoulcraft:awning_green
give @s ghoulcraft:awning_lblue
give @s ghoulcraft:awning_lgray
give @s ghoulcraft:awning_lime
give @s ghoulcraft:awning_orange
give @s ghoulcraft:awning_magenta
give @s ghoulcraft:awning_purple
give @s ghoulcraft:awning_pink
give @s ghoulcraft:awning_red
give @s ghoulcraft:awning_white
give @s ghoulcraft:awning_yellow
gamerule sendcommandfeedback true