gamerule sendcommandfeedback false
give @s ghoulcraft:shutter_black
give @s ghoulcraft:shutter_blue
give @s ghoulcraft:shutter_brown
give @s ghoulcraft:shutter_cyan
give @s ghoulcraft:shutter_gray
give @s ghoulcraft:shutter_green
give @s ghoulcraft:shutter_lblue
give @s ghoulcraft:shutter_lgray
give @s ghoulcraft:shutter_lime
give @s ghoulcraft:shutter_orange
give @s ghoulcraft:shutter_magenta
give @s ghoulcraft:shutter_purple
give @s ghoulcraft:shutter_pink
give @s ghoulcraft:shutter_red
give @s ghoulcraft:shutter_white
give @s ghoulcraft:shutter_yellow
gamerule sendcommandfeedback true