gamerule sendcommandfeedback false
give @s ghoulcraft:windowbox
give @s ghoulcraft:windowbox_allium
give @s ghoulcraft:windowbox_azure
give @s ghoulcraft:windowbox_brownm
give @s ghoulcraft:windowbox_cornflower
give @s ghoulcraft:windowbox_daisy
give @s ghoulcraft:windowbox_dandelion
give @s ghoulcraft:windowbox_lilac
give @s ghoulcraft:windowbox_lily
give @s ghoulcraft:windowbox_otulip
give @s ghoulcraft:windowbox_orchid
give @s ghoulcraft:windowbox_peony
give @s ghoulcraft:windowbox_ptulip
give @s ghoulcraft:windowbox_poppy
give @s ghoulcraft:windowbox_redm
give @s ghoulcraft:windowbox_rtulip
give @s ghoulcraft:windowbox_rose
give @s ghoulcraft:windowbox_wtulip
give @s ghoulcraft:windowbox_wrose
gamerule sendcommandfeedback true